### ISSUE TITLE
useStorage to return [value, set]

### ISSUE THREAD

**Issue by hasnat** [hacknlove/usestorage#1]
similar standard useState may be useStorage should send back [value, set] instead of just value ?

**Comment by hacknlove** [comment]
Good point, even if it is trivial to use chrome.storage.sync.set it is a
good idea to stick to the useState standard.

I'll do that.

**Comment by hacknlove** [comment]
Done, 

It was a quick fix that should work, but I have not tested it yet.

**Comment by hasnat** [comment]
That sure was quick, big thanks.

**Comment by hacknlove** [comment]
Tested now, it has a bug and it is fixed now.

Please update to 1.1.1

**Comment by hasnat** [comment]
Great thanks.
